trigger:
  branches:
    include:
      - devops

pool:
  vmImage: 'ubuntu-latest'

variables:
  AZURE_ARTIFACTS_ENV_ACCESS_TOKEN: 'qtn6dfiua2bbk2aghvvvz7xppuxamps5kgqk76vov3r6px25b3fa'
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build & push the image 
  jobs:  
  - job: Build
    displayName: Build Job
    steps:
    - task: Docker@2
      displayName: Docker login
      inputs:
       command: 'login'
       containerRegistry: login-to-hub
    - task: Docker@2
      displayName: Build & pusing the image
      inputs:
        repository: '1383/azure_pipeline'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'